shared:
  image: node:14
  settings:
    slack:
      channels:
        - test-sd-notifications
      statuses:
        - SUCCESS
        - FAILURE
        - QUEUED
        - RUNNING
      minimized: false
jobs:
  main:
    requires: [ ~pr, ~commit ]
    steps:
      - echo hi
