shared:
  image: node:18
jobs:
  main:
      requires: [ ~commit ]
      steps:
        - sleep: meta set build.warning.message "this is a warning message"
        - fail: return 1
  green:
      requires: [main]
      steps:
        - hello: echo hello
