shared:
  image: node:18
jobs:
  main:
      requires: [ ~commit ]
      steps:
        - sleep: meta set build.warning "this is warning"
  green:
      requires: [main]
      steps:
        - hello: echo hello
