shared:
  image: node:18
jobs:
  main:
      requires: [ ~pr, ~commit ]
      steps:
        - warn: meta set build.warning.warn "this is a warning"
        - alert: meta set build.warning.alert "this is an alert"
