shared:
  image: node:18
jobs:
  main:
      requires: [ ~commit ]
      steps:
        - inject: |
           meta set build.warning.message "<img src=\"#notanimage\" onerror=\"alert('unsafe script injection from warning!')\" />"
