shared:
  image: node:18
jobs:
  main:
      requires: [ ~commit ]
      steps:
        - sleep: |
          meta set build.warning.message "this is a warning message"
          meta set build.warning.anotherMessage "this is a warning message"
