shared:
  image: node:18
jobs:
  main:
      requires: [ ~commit ]
      steps:
        - sleep: sleep 10
  fan-5-60:
      steps:
        - sleep: sleep 1
  fan-5-30-60:
      steps:
        - sleep: sleep 1
  fan-5-10-15-30-60:
      steps:
        - sleep: sleep 1
  fan-in-5:
      requires: [ ~fan-5-60, ~fan-5-30-60, ~fan-5-10-15-30-60 ]
      steps:
        - sleep: sleep 5
  fan-in-10:
      requires: [ ~fan-in-5, ~fan-5-10-15-30-60 ]
      steps:
        - sleep: sleep 10
  fan-in-15:
      requires: [ ~fan-5-10-15-30-60 ]
      steps:
        - sleep: sleep 15
  fan-in-30:
      requires: [ ~fan-5-30-60, ~fan-5-10-15-30-60 ]
      steps:
        - sleep: sleep 30
  fan-in-60:
      requires: [ ~fan-5-60, ~fan-5-30-60, ~fan-5-10-15-30-60 ]
      steps:
        - sleep: sleep 60
  join:
      requires: [~fan-in-5, ~fan-in-10, ~fan-in-15, ~fan-in-30, ~fan-in-60]
      blockedBy: [~fan-in-5, ~fan-in-10, ~fan-in-15, ~fan-in-30, ~fan-in-60]
      steps:
          - hello: echo hello
