shared:
  image: node:18
jobs:
  main:
      requires: [ ~pr, ~commit ]
      steps:
        - warn: meta set meta.warning.warn "this is a warning"
        - sleep: sleep 600
        - alert: meta set meta.warning.alert "this is an alert"
