shared:
    image: node:12
    settings:
        email:
          addresses: [foobarnotvalid@gmail.com]
          statuses: [SUCCESS, FAILURE]
        slack:
          channels:
           - 'test-notifications'
          statuses:
           - SUCCESS
           - FAILURE
jobs:
    main:
        annotations:
            screwdriver.cd/buildPeriodically: H(6-7) * * * *
        requires: [~pr, ~commit]
        steps:
              - echo: echo hi
#             - validate: sd-cmd validate -f sd-command.yaml
#     publish:
#         requires: [main]
#         steps:
#             - publish: sd-cmd publish -f sd-command.yaml -t latest
#     promote:
#         requires: [publish]
#         steps:
#             - promote: sd-cmd promote foo/bar latest stable
