shared:
  image: node:18
jobs:
  main:
      requires: [ ~commit ]
      steps:
        - setWarning: meta set build.warning.message "<img src=\"#notanimage\" onerror=\"alert('unsafe script injection from warning!')\" />"
        - setAnotherWarning: meta set build.warning.anotherMessage "this is another warning message"
