shared:
  image: node:14
jobs:
  main:
    annotations:
      screwdriver.cd/blockedBySameJob: false
      screwdriver.cd/blockedBySameJobWaitTime: 0
    requires: [ ~pr, ~commit ]
    steps:
      - sleep 60
