shared:
  image: node:18
jobs:
  main:
      requires: [ ~commit ]
      steps:
        - warn: meta set build.warn "this is a warning"
        - alert: meta set build.alert "this is an alert"
  follow:
      requires: [ ~main ]
      steps:
        - warn: echo hello
  main2:
      requires: [ ~pr ]
      steps:
        - coverage: meta set meta.summary.coverage "Coverage increased by 15%"
        - markdown: meta set meta.summary.markdown "this markdown comment is **bold** and *italic*"
