shared:
    image: node:12

jobs:
  main:
    requires: [~pr, ~commit]
    steps:
      - noop: echo hello
      - http: echo http://github.com/
      - https: echo https://github.com/
  fail:
    requires: [main]
    steps:
      - noop: return 127
  pass:
    requires: [main]
    steps:
      - noop: echo hello
  main:
    requires: [pass, fail]
    steps:
      - noop: echo hello
