shared:
  image: node:18
jobs:
  main:
      requires: [ ~commit ]
      steps:
        - sleep: meta set build.warning.message "this is warning"
        - a: meta set build.warning.warn "warn"
  green:
      requires: [main]
      steps:
        - hello: echo hello
