shared:
  image: node:18
jobs:
  main:
      requires: [ ~commit ]
      steps:
        - setWarning: meta set build.warning.message "this is a warning message"
        - setAnotherWarning: meta set build.warning.message "this is a warning message"
