shared:
  image: node:18
jobs:
  main:
      requires: [ ~commit ]
      steps:
        - setWarning: meta set build.warning.message "this is a warning message"
        - setAnotherWarning: meta set build.warning.anotherMessage "this is another warning message"
  main1:
      requires: [~pr]
      steps:
          - check-pr: meta set build.warning.Warning "E2E tests have been skipped and will run once the PR is approved."
  main2:
      requires: [~pr]
      steps:
          - check-pr: meta set build.warning.Warning "E2E tests have been skipped and will run once the PR is approved."
  main3:
      requires: [~pr]
      steps:
          - check-pr: meta set build.warning.Warning "E2E tests have been skipped and will run once the PR is approved."
  main4:
      requires: [~pr]
      steps:
          - check-pr: meta set build.warning.Warning "E2E tests have been skipped and will run once the PR is approved."
