shared:
  image: node:18
jobs:
  main:
      requires: [ ~commit ]
      steps:
        - warn: meta set meta.warning.warn "this is a warning"
        - alert: meta set meta.warning.alert "this is an alert"
  main2:
      requires: [ ~pr ]
      steps:
        - coverage: meta set meta.summary.coverage "Coverage increased by 155%"
        - markdown: meta set meta.summary.markdown "this markdown comment is **bold** and *italic*"
        - split: meta set meta.splitComments "split it"
