shared:
    image: node:12
jobs:
    main:
        requires: [~pr, ~commit]
        steps:
              - echo: echo hi
#             - validate: sd-cmd validate -f sd-command.yaml
#     publish:
#         requires: [main]
#         steps:
#             - publish: sd-cmd publish -f sd-command.yaml -t latest
#     promote:
#         requires: [publish]
#         steps:
#             - promote: sd-cmd promote foo/bar latest stable
